# Generated by Django 6.0.3 on 2026-04-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0003_remove_design_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='category',
            field=models.CharField(choices=[('living_room', 'Living Room'), ('bedroom', 'Bedroom'), ('kitchen', 'Kitchen'), ('office', 'Office'), ('modular_furniture', 'Modular Furniture'), ('lighting_decor', 'Lighting & Decor'), ('bathroom', 'Bathroom'), ('balcony', 'Balcony & Foyer'), ('full_home', 'Full Home'), ('luxury', 'Luxury'), ('renovation', 'Renovation')], max_length=50),
        ),
    ]
